%run the code to test all the examples
clear
MatDEMfile('examplesModel/user_BoxFiberCouple1.m');
MatDEMfile('examplesModel/user_BoxFiberCouple2.m');
MatDEMfile('examplesModel/user_BoxFiberCouple3.m');
MatDEMfile('examplesModel/user_BoxLayer1.m');
MatDEMfile('examplesModel/user_BoxLayer2.m');
MatDEMfile('examplesModel/user_BoxWord1.m');
MatDEMfile('examplesModel/user_BoxWord2.m');
MatDEMfile('examplesModel/user_BoxWord3.m');
MatDEMfile('examplesModel/user_Cable.m');
MatDEMfile('examplesModel/user_Columns1.m');
MatDEMfile('examplesModel/user_Columns2.m');
MatDEMfile('examplesModel/user_ColumnShow.m');
MatDEMfile('examplesModel/user_createSurfaceNet.m');
MatDEMfile('examplesModel/user_DropOnNet.m');
MatDEMfile('examplesModel/user_Function2Object.m');
MatDEMfile('examplesModel/user_Functions.m');
MatDEMfile('examplesModel/user_L2MicroParticle1.m');
MatDEMfile('examplesModel/user_L2MicroParticle2.m');
MatDEMfile('examplesModel/user_LineModel.m');
MatDEMfile('examplesModel/user_modelAnchor.m');
MatDEMfile('examplesModel/user_modelExample.m');
MatDEMfile('examplesModel/user_modelFiber.m');